### ISSUE TITLE
Console error: TypeError: $.isNumeric is not a function

### ISSUE THREAD

**Issue by cucha77** [BrandonCKrueger/angular-currency#5]
I have the following error in the browser console:
TypeError: $.isNumeric is not a function
    at updateElement (angular-currency.js:27)

I solved it by changing the line 30:
`if ($.isNumeric(newVal)) {`

by

`if (jQuery.isNumeric(newVal)) {`

In may case, It is possible that the error occurs due to a conflict of libraries

**Comment by BrandonCKrueger** [comment]
Thanks for pointing this out!

[Commit 6214e204863fe74dda2c8c822beddeb238b0d9ae](https://github.com/BrandonCKrueger/angular-currency/commit/6214e204863fe74dda2c8c822beddeb238b0d9ae) should fix that by using regular javascript to check if a value is numeric.
